### ISSUE TITLE
BUG: potential attribute error

### ISSUE THREAD

**Issue by aburrell** [ipython/traitlets#684]
I encountered this after upgrading ipython.  An AttributeError in traitlets has stopped ipython from opening.  I am not quite sure what's going on in the code after a brief peak, so thought I would bring it to your attention.

```
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitlets/config/loader.py", line 933, in __call__
    namespace._flags.append(self.flag)
AttributeError: 'Namespace' object has no attribute '_flags'
```

I am running OS X Mojave, python 3.9.8, and traitlets version 5.1.0.  Please let me know if I can provide any more information or perform any tests that may be useful.

**Comment by ktowen** [comment]
I'm having the same error. It started after upgrading Python from 3.9.7 to 3.9.8

**Comment by mocurin** [comment]
Same issue. OS X Big Sur, launching notebooks inside VSCode on python 3.9.8 & 3.10.0 seems broken

**Comment by pmadhikar** [comment]
Did anyone have any luck with fixing this bug? I have the same problem.

**Comment by rmorshea** [comment]
@Carreau it looks like Jupyter should bump the [minimum version of `traitlets`](https://github.com/jupyter/notebook/blob/master/setup.py#L119) is depends on.
